// "use client"
import Navbar from "@/components/Navbar";
import "./globals.css";
import GetInTouch from "@/components/GetInTouch";


export const metadata = {
  title: "Rushi | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Navbar />
        {children}
        
      </body>
    </html>
  );
}
