export const TopProjects = [
  {
    id: 1,
    title: "AI-Based Personalized Course Generator",
    description:
      "An AI-powered platform that generates complete courses on any topic with dynamic adaptability. Includes custom course generation using Google Gemini (RAG), fork & merge features like GitHub, and dynamic AI-based content adaptation.",
    images: {
      poster_img: "https://i.ibb.co/rGKmTLFn/Screenshot-38.png",
      carosel_img: [
        "https://i.ibb.co/whsrsLm8/Screenshot-39.png",
        "https://i.ibb.co/YBW0KrWj/Screenshot-40.png",
        "https://i.ibb.co/NdFh3mLS/Screenshot-41.png",
        "https://i.ibb.co/vCH2HR3j/Screenshot-42.png",
        "https://i.ibb.co/jkHVNJnx/Screenshot-43.png",
        "https://i.ibb.co/fG19nDLk/Screenshot-44.png",
        "https://i.ibb.co/ZR7R1Fc3/Screenshot-45.png",
        "https://i.ibb.co/YBWxDQsb/Screenshot-46.png",
        "https://i.ibb.co/214P393N/Screenshot-47.png",
        "https://i.ibb.co/FP8jrzR/Screenshot-48.png",
      ],
    },
    demo_link: "https://supersonicsai-v1.vercel.app/",
  },
  {
    id: 2,
    title: "E-Commerce Website for Women's Clothing",
    description:
      "An advanced e-commerce platform with full-featured shopping & admin capabilities. Features include search, categories, favourites, cart, order management. Admin Panel includes user, product, review, and category management.",
    images: {
      poster_img: "https://i.ibb.co/PGtsZybw/Screenshot-30.png",
      carosel_img: [
        "https://i.ibb.co/PGtsZybw/Screenshot-30.png",
        "https://i.ibb.co/Xxd7vJ12/Screenshot-31.png",
        "https://i.ibb.co/6RqK39hS/Screenshot-32.png",
        "https://i.ibb.co/SwDvt1BQ/Screenshot-33.png",
        "https://i.ibb.co/Ndym2c8H/Screenshot-34.png",
        "https://i.ibb.co/fVZJBhzw/Screenshot-35.png",
        "https://i.ibb.co/v4mWkfy7/Screenshot-36.png",
        "https://i.ibb.co/99H2sdvG/Screenshot-37.png",
        "https://i.ibb.co/ycsL3KzW/Screenshot-2025-07-09-010844.png",
        "https://i.ibb.co/k6hYgrGr/Screenshot-2025-07-09-010907.png",
        "https://i.ibb.co/Q7WZj5gc/Screenshot-2025-07-09-010916.png",
        "https://i.ibb.co/67MfBP9S/Screenshot-2025-07-09-010923.png",
        "https://i.ibb.co/ns3GGhQf/Screenshot-2025-07-09-010933.png",
        "https://i.ibb.co/99MM0bn9/Screenshot-2025-07-09-010940.png",
        "https://i.ibb.co/fGY5Kc4p/Screenshot-2025-07-09-010950.png",
        "https://i.ibb.co/yBsnWSfX/Screenshot-2025-07-09-011011.png",
      ],
    },
    demo_link: "https://blush-shop.vercel.app/",
  },

  {
    id: 3,
    title: "AI-Based Resume Analyzer",
    description:
      "An intelligent resume evaluation and career guidance system powered by AI. Features include resume scoring, keyword analysis, ATS optimization, job-role matching, skill/course recommendations, and job suggestions.",
    images: {
      poster_img: "https://i.ibb.co/Psg4PCd7/Screenshot-49.png",
      carosel_img: [
        "https://i.ibb.co/XkCmpCkT/Screenshot-50.png",
        "https://i.ibb.co/jPLdZtzW/Screenshot-51.png",
        "https://i.ibb.co/B56GGdDg/Screenshot-52.png",
        "https://i.ibb.co/8gCFQMN4/Screenshot-53.png",
        "https://i.ibb.co/4ZZ77rgr/Screenshot-54.png",
        "https://i.ibb.co/1tRTBB3Y/Screenshot-55.png",
        "https://i.ibb.co/1JJFH1KF/Screenshot-56.png",
        "https://i.ibb.co/CK0GHxDk/Screenshot-57.png",
        "https://i.ibb.co/twXk3XNk/Screenshot-58.png",
        "https://i.ibb.co/8DhYW7wy/Screenshot-59.png",
        "https://i.ibb.co/TMLMjjRH/Screenshot-60.png",
        "https://i.ibb.co/TqKBMByR/Screenshot-61.png",
        "https://i.ibb.co/5X6bVyHx/Screenshot-62.png",
        "https://i.ibb.co/Hp3qj7Y4/Screenshot-63.png",
        "https://i.ibb.co/yct50x8X/Screenshot-64.png",
        "https://i.ibb.co/N2M6ZBxq/Screenshot-65.png",
        "https://i.ibb.co/gZKsxb6v/Screenshot-66.png",
        "https://i.ibb.co/h1ZBN19P/Screenshot-67.png",
        "https://i.ibb.co/LzMQrZbf/Screenshot-68.png",
        "https://i.ibb.co/My8x6ngH/Screenshot-69.png",
        "https://i.ibb.co/YTpFK7md/Screenshot-70.png",
        "https://i.ibb.co/nqsmtxNX/Screenshot-71.png",
        "https://i.ibb.co/LhpZZS0Z/Screenshot-72.png",
      ],
    },
    demo_link: "https://forge-ai-seven.vercel.app/",
  },
  {
    id: 1,
    title: "AI-Based Personalized Course Generator",
    description:
      "An AI-powered platform that generates complete courses on any topic with dynamic adaptability. Includes custom course generation using Google Gemini (RAG), fork & merge features like GitHub, and dynamic AI-based content adaptation.",
    images: {
      poster_img: "https://i.ibb.co/rGKmTLFn/Screenshot-38.png",
      carosel_img: [
        "https://i.ibb.co/whsrsLm8/Screenshot-39.png",
        "https://i.ibb.co/YBW0KrWj/Screenshot-40.png",
        "https://i.ibb.co/NdFh3mLS/Screenshot-41.png",
        "https://i.ibb.co/vCH2HR3j/Screenshot-42.png",
        "https://i.ibb.co/jkHVNJnx/Screenshot-43.png",
        "https://i.ibb.co/fG19nDLk/Screenshot-44.png",
        "https://i.ibb.co/ZR7R1Fc3/Screenshot-45.png",
        "https://i.ibb.co/YBWxDQsb/Screenshot-46.png",
        "https://i.ibb.co/214P393N/Screenshot-47.png",
        "https://i.ibb.co/FP8jrzR/Screenshot-48.png",
      ],
    },
    demo_link: "https://supersonicsai-v1.vercel.app/",
  },
  {
    id: 2,
    title: "E-Commerce Website for Women's Clothing",
    description:
      "An advanced e-commerce platform with full-featured shopping & admin capabilities. Features include search, categories, favourites, cart, order management. Admin Panel includes user, product, review, and category management.",
    images: {
      poster_img: "https://i.ibb.co/PGtsZybw/Screenshot-30.png",
      carosel_img: [
        "https://i.ibb.co/PGtsZybw/Screenshot-30.png",
        "https://i.ibb.co/Xxd7vJ12/Screenshot-31.png",
        "https://i.ibb.co/6RqK39hS/Screenshot-32.png",
        "https://i.ibb.co/SwDvt1BQ/Screenshot-33.png",
        "https://i.ibb.co/Ndym2c8H/Screenshot-34.png",
        "https://i.ibb.co/fVZJBhzw/Screenshot-35.png",
        "https://i.ibb.co/v4mWkfy7/Screenshot-36.png",
        "https://i.ibb.co/99H2sdvG/Screenshot-37.png",
        "https://i.ibb.co/ycsL3KzW/Screenshot-2025-07-09-010844.png",
        "https://i.ibb.co/k6hYgrGr/Screenshot-2025-07-09-010907.png",
        "https://i.ibb.co/Q7WZj5gc/Screenshot-2025-07-09-010916.png",
        "https://i.ibb.co/67MfBP9S/Screenshot-2025-07-09-010923.png",
        "https://i.ibb.co/ns3GGhQf/Screenshot-2025-07-09-010933.png",
        "https://i.ibb.co/99MM0bn9/Screenshot-2025-07-09-010940.png",
        "https://i.ibb.co/fGY5Kc4p/Screenshot-2025-07-09-010950.png",
        "https://i.ibb.co/yBsnWSfX/Screenshot-2025-07-09-011011.png",
      ],
    },
    demo_link: "https://blush-shop.vercel.app/",
  },

  {
    id: 3,
    title: "AI-Based Resume Analyzer",
    description:
      "An intelligent resume evaluation and career guidance system powered by AI. Features include resume scoring, keyword analysis, ATS optimization, job-role matching, skill/course recommendations, and job suggestions.",
    images: {
      poster_img: "https://i.ibb.co/Psg4PCd7/Screenshot-49.png",
      carosel_img: [
        "https://i.ibb.co/XkCmpCkT/Screenshot-50.png",
        "https://i.ibb.co/jPLdZtzW/Screenshot-51.png",
        "https://i.ibb.co/B56GGdDg/Screenshot-52.png",
        "https://i.ibb.co/8gCFQMN4/Screenshot-53.png",
        "https://i.ibb.co/4ZZ77rgr/Screenshot-54.png",
        "https://i.ibb.co/1tRTBB3Y/Screenshot-55.png",
        "https://i.ibb.co/1JJFH1KF/Screenshot-56.png",
        "https://i.ibb.co/CK0GHxDk/Screenshot-57.png",
        "https://i.ibb.co/twXk3XNk/Screenshot-58.png",
        "https://i.ibb.co/8DhYW7wy/Screenshot-59.png",
        "https://i.ibb.co/TMLMjjRH/Screenshot-60.png",
        "https://i.ibb.co/TqKBMByR/Screenshot-61.png",
        "https://i.ibb.co/5X6bVyHx/Screenshot-62.png",
        "https://i.ibb.co/Hp3qj7Y4/Screenshot-63.png",
        "https://i.ibb.co/yct50x8X/Screenshot-64.png",
        "https://i.ibb.co/N2M6ZBxq/Screenshot-65.png",
        "https://i.ibb.co/gZKsxb6v/Screenshot-66.png",
        "https://i.ibb.co/h1ZBN19P/Screenshot-67.png",
        "https://i.ibb.co/LzMQrZbf/Screenshot-68.png",
        "https://i.ibb.co/My8x6ngH/Screenshot-69.png",
        "https://i.ibb.co/YTpFK7md/Screenshot-70.png",
        "https://i.ibb.co/nqsmtxNX/Screenshot-71.png",
        "https://i.ibb.co/LhpZZS0Z/Screenshot-72.png",
      ],
    },
    demo_link: "https://forge-ai-seven.vercel.app/",
  },
  {
    id: 1,
    title: "AI-Based Personalized Course Generator",
    description:
      "An AI-powered platform that generates complete courses on any topic with dynamic adaptability. Includes custom course generation using Google Gemini (RAG), fork & merge features like GitHub, and dynamic AI-based content adaptation.",
    images: {
      poster_img: "https://i.ibb.co/rGKmTLFn/Screenshot-38.png",
      carosel_img: [
        "https://i.ibb.co/whsrsLm8/Screenshot-39.png",
        "https://i.ibb.co/YBW0KrWj/Screenshot-40.png",
        "https://i.ibb.co/NdFh3mLS/Screenshot-41.png",
        "https://i.ibb.co/vCH2HR3j/Screenshot-42.png",
        "https://i.ibb.co/jkHVNJnx/Screenshot-43.png",
        "https://i.ibb.co/fG19nDLk/Screenshot-44.png",
        "https://i.ibb.co/ZR7R1Fc3/Screenshot-45.png",
        "https://i.ibb.co/YBWxDQsb/Screenshot-46.png",
        "https://i.ibb.co/214P393N/Screenshot-47.png",
        "https://i.ibb.co/FP8jrzR/Screenshot-48.png",
      ],
    },
    demo_link: "https://supersonicsai-v1.vercel.app/",
  },
  {
    id: 2,
    title: "E-Commerce Website for Women's Clothing",
    description:
      "An advanced e-commerce platform with full-featured shopping & admin capabilities. Features include search, categories, favourites, cart, order management. Admin Panel includes user, product, review, and category management.",
    images: {
      poster_img: "https://i.ibb.co/PGtsZybw/Screenshot-30.png",
      carosel_img: [
        "https://i.ibb.co/PGtsZybw/Screenshot-30.png",
        "https://i.ibb.co/Xxd7vJ12/Screenshot-31.png",
        "https://i.ibb.co/6RqK39hS/Screenshot-32.png",
        "https://i.ibb.co/SwDvt1BQ/Screenshot-33.png",
        "https://i.ibb.co/Ndym2c8H/Screenshot-34.png",
        "https://i.ibb.co/fVZJBhzw/Screenshot-35.png",
        "https://i.ibb.co/v4mWkfy7/Screenshot-36.png",
        "https://i.ibb.co/99H2sdvG/Screenshot-37.png",
        "https://i.ibb.co/ycsL3KzW/Screenshot-2025-07-09-010844.png",
        "https://i.ibb.co/k6hYgrGr/Screenshot-2025-07-09-010907.png",
        "https://i.ibb.co/Q7WZj5gc/Screenshot-2025-07-09-010916.png",
        "https://i.ibb.co/67MfBP9S/Screenshot-2025-07-09-010923.png",
        "https://i.ibb.co/ns3GGhQf/Screenshot-2025-07-09-010933.png",
        "https://i.ibb.co/99MM0bn9/Screenshot-2025-07-09-010940.png",
        "https://i.ibb.co/fGY5Kc4p/Screenshot-2025-07-09-010950.png",
        "https://i.ibb.co/yBsnWSfX/Screenshot-2025-07-09-011011.png",
      ],
    },
    demo_link: "https://blush-shop.vercel.app/",
  },

  {
    id: 3,
    title: "AI-Based Resume Analyzer",
    description:
      "An intelligent resume evaluation and career guidance system powered by AI. Features include resume scoring, keyword analysis, ATS optimization, job-role matching, skill/course recommendations, and job suggestions.",
    images: {
      poster_img: "https://i.ibb.co/Psg4PCd7/Screenshot-49.png",
      carosel_img: [
        "https://i.ibb.co/XkCmpCkT/Screenshot-50.png",
        "https://i.ibb.co/jPLdZtzW/Screenshot-51.png",
        "https://i.ibb.co/B56GGdDg/Screenshot-52.png",
        "https://i.ibb.co/8gCFQMN4/Screenshot-53.png",
        "https://i.ibb.co/4ZZ77rgr/Screenshot-54.png",
        "https://i.ibb.co/1tRTBB3Y/Screenshot-55.png",
        "https://i.ibb.co/1JJFH1KF/Screenshot-56.png",
        "https://i.ibb.co/CK0GHxDk/Screenshot-57.png",
        "https://i.ibb.co/twXk3XNk/Screenshot-58.png",
        "https://i.ibb.co/8DhYW7wy/Screenshot-59.png",
        "https://i.ibb.co/TMLMjjRH/Screenshot-60.png",
        "https://i.ibb.co/TqKBMByR/Screenshot-61.png",
        "https://i.ibb.co/5X6bVyHx/Screenshot-62.png",
        "https://i.ibb.co/Hp3qj7Y4/Screenshot-63.png",
        "https://i.ibb.co/yct50x8X/Screenshot-64.png",
        "https://i.ibb.co/N2M6ZBxq/Screenshot-65.png",
        "https://i.ibb.co/gZKsxb6v/Screenshot-66.png",
        "https://i.ibb.co/h1ZBN19P/Screenshot-67.png",
        "https://i.ibb.co/LzMQrZbf/Screenshot-68.png",
        "https://i.ibb.co/My8x6ngH/Screenshot-69.png",
        "https://i.ibb.co/YTpFK7md/Screenshot-70.png",
        "https://i.ibb.co/nqsmtxNX/Screenshot-71.png",
        "https://i.ibb.co/LhpZZS0Z/Screenshot-72.png",
      ],
    },
    demo_link: "https://forge-ai-seven.vercel.app/",
  },
];
